version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "128mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./frigate/config:/config
      - ./frigate/videos:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
    networks:
      - frigate
    depends_on:
      - mqtt

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:2.0
    volumes:
      - ./mosquitto/logs/:/mosquitto/logs/
      - ./mosquitto/conf/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped
    networks:
      - frigate
    ports:
      - 1883:1883

  signalapi:
    container_name: signalapi
    image: bbernhard/signal-cli-rest-api:latest
    environment:
      - MODE=native
      - AUTO_RECEIVE_SCHEDULE=0 22 * * *
    ports:
      - "8180:8080"
    volumes:
      - ./signal-cli-config:/home/.local/share/signal-cli
    restart: unless-stopped
    depends_on:
      - mqtt
    networks:
      - frigate

  send_message:
    container_name: send_message
    image: send_message:latest
    networks:
      - frigate
    restart: unless-stopped
    environment:
      SIGNAL_NUMBER: ${SIGNAL_NUMBER}
      SIGNAL_RECIPIENT: ${SIGNAL_RECIPIENT}

networks:
  frigate:
